// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZ05wVLRilqyb8smPvpiF2VYtn654xylQ',
    appId: '1:427102359200:web:1e62b64e8ee38c099b83c5',
    messagingSenderId: '427102359200',
    projectId: 'mynotes-aa554',
    authDomain: 'mynotes-aa554.firebaseapp.com',
    storageBucket: 'mynotes-aa554.appspot.com',
    measurementId: 'G-7060F929XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB_YIUKmPyXp7TfWDm0zAH6wTFPRIfKp0',
    appId: '1:427102359200:android:2725d5d7f85eb58a9b83c5',
    messagingSenderId: '427102359200',
    projectId: 'mynotes-aa554',
    storageBucket: 'mynotes-aa554.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMHuhgAL4lxhkR5UMSjByglJlaa6T0guY',
    appId: '1:427102359200:ios:f58318ac1f5478849b83c5',
    messagingSenderId: '427102359200',
    projectId: 'mynotes-aa554',
    storageBucket: 'mynotes-aa554.appspot.com',
    iosBundleId: 'com.firstProject.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMHuhgAL4lxhkR5UMSjByglJlaa6T0guY',
    appId: '1:427102359200:ios:f58318ac1f5478849b83c5',
    messagingSenderId: '427102359200',
    projectId: 'mynotes-aa554',
    storageBucket: 'mynotes-aa554.appspot.com',
    iosBundleId: 'com.firstProject.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZ05wVLRilqyb8smPvpiF2VYtn654xylQ',
    appId: '1:427102359200:web:6be4e90cb6fc1ea29b83c5',
    messagingSenderId: '427102359200',
    projectId: 'mynotes-aa554',
    authDomain: 'mynotes-aa554.firebaseapp.com',
    storageBucket: 'mynotes-aa554.appspot.com',
    measurementId: 'G-91T8WZXLJ3',
  );
}
